### ISSUE TITLE
실행하려면 뭘 해야 하나요?

### ISSUE THREAD

**Issue by Magnus111111** [nanikit/eztrans-server#1]
명령 프롬프트로 App.xaml 도 안되고 MainWindow.xaml 도 안되던데

**Comment by nanikit** [comment]
https://github.com/nanikit/eztrans-server/releases/tag/v200304
여기서 실행파일 받으시면 될 거예요.

**Comment by nanikit** [comment]
문제 있으면 다시 열어주세요.
