### ISSUE TITLE
이 프로젝트는 어떤 라이센스로 배포되나요?

### ISSUE THREAD

**Issue by handbros** [nanikit/eztrans-server#2]
가능하다면 이 레포지토리의 코드를 활용해보고 싶은데 아무래도 라이센스가 없다보니까 불안한 감이 있네요... ㅎㅎ
어떤 라이센스로 배포중이신지 알려주실 수 있을까요? :D

**Comment by jeiea** [comment]
아 제가 라이선스를 안 달아놨네요. MIT을 생각하고 있는데 조만간 업데이트하겠습니다.

**Comment by nanikit** [comment]
제가 라이선스를 빠뜨렸네요. MIT을 생각하고 있고 조만간 업데이트 할게요.

**Comment by handbros** [comment]
재사용 허락해주셔서 감사드리고, 잘 사용하도록 하겠습니다!
감사합니다! 😍
