### ISSUE TITLE
Ehnd를 찾지 못한다고 합니다.

### ISSUE THREAD

**Issue by ghost** [nanikit/eztrans-server#4]
v200304는 잘되는데 v211218은 Ehnd를 찾지 못한다고 하면서 안되네요.

FATAL: Ehnd를 찾지 못했습니다 
    at Nanikit.Ehnd.EhndInterop.LoadDll(String dllPath)
   at Nanikit.Ehnd.Ehnd..ctor(String dllPath)
   at EztransServer.Core.Translator.EhndTranslator..ctor(String dllPath)
   at EztransServer.Gui.HttpServerVM.Restart()

**Comment by nanikit** [comment]
제가 지금 떠올릴 수 있는 건 이전 이지트랜스 서버 실행파일이 이지트랜스 설치 경로 안에 들어있어서 이지트랜스를 찾을 수 있었고 새 버전은 그렇지 않아서 찾지 못한다는 경우의 수밖에 없네요. 만약 그렇다면 위치를 똑같이 옮겨서 실행해주시면 됩니다.
또 하나는 이지트랜스를 한번 실행해보시고 실행하는 것도 시도할만할 것 같아요.

위 두 가지 시도해보시고 알려주세요.

**Comment by ghost** [comment]
둘 다 해봤는데 안되네요.

**Comment by nanikit** [comment]
그럼 진단용 패치를 배포해야할 것 같네요. 새로 릴리즈하면 다시 코멘트 남길게요.

**Comment by ghost** [comment]
혹시 설치 경로가 C드라이브가 아니면 안될수도 있나요?

**Comment by nanikit** [comment]
아뇨. 현 구현에서 이지트랜스를 검색하는 경로는 다음이에요.
- 이지트랜스가 실행될 때 레지스트리에 기록하는 경로
- 이지트랜스 기본 설치 경로
- 실행파일 상위 모든 디렉토리

**Comment by nanikit** [comment]
https://github.com/nanikit/eztrans-server/releases/tag/v211219
여기 파일로 실행했을 때 어떻게 나오는지 알려주시겠어요? 이지트랜스 설치경로 안, 바깥에서 어떻게 안 되는지 알려주시면 좋을 것 같아요.

**Comment by ghost** [comment]
이지트랜스 설치 경로 안에서는 잘 되고, 바깥에서는 이렇게 나오면서 안되네요.

Ehnd를 찾지 못했습니다
C:\Program Files (x86)\ChangShinSoft\ezTrans XP\J2KEngine.dll: not exists
E:\J2KEngine.dll: not exists

**Comment by nanikit** [comment]
이지트랜스를 C가 아닌 다른 경로에 설치한 것 같네요.
- 이지트랜스를 직접 실행해본 적이 있을까요? 없다면 일단 한 번 실행해주세요.
- 지금 쓰는 운영체제가 어떻게 되나요?

**Comment by ghost** [comment]
설치 경로는 E드라이브가 맞고, 이지트랜스를 실행했을 때도 설치 경로 바깥에서는 위에처럼 뜹니다.
운영체제는 윈도우11 입니다.

**Comment by nanikit** [comment]
윈도 11은 제가 아직 테스트를 해보지 않았는데 시간이 필요할 것 같네요. 제보 고맙습니다.

**Comment by nanikit** [comment]
윈도 11에서 테스트한 결과 레지스트리로 이지트랜스를 찾을 수 있었습니다. 새 버전만 문제가 생기는 걸 설명하지 못하겠네요.
제가 재현이 불가능하기에 추가 정보가 없으면 더 진행은 힘들 듯 합니다.

**Comment by ghost** [comment]
근데 v200304도 이지트랜스 설치 경로에 없으면 이지트랜스를 찾지 못한다고 하면서 안되서 이지트랜스 설치 경로에 놓고 쓰긴 했어요.
이게 이지트랜스 설치 경로가 C드라이브가 아니라 그런 건가요?

**Comment by nanikit** [comment]
이지트랜스를 한 번 실행하셔야 이지트랜스가 어디있든 감지해서 실행할 수 있습니다. 이지트랜스 설치 경로에 있는 eztrans.exe
파일을 실행하는 걸 말해요.
제가 테스트했을 땐 이 기능이 잘 작동했는데 왜 안되는 지는 이전에 말했듯 정보가 부족해 알기 힘들 것 같습니다.

**Comment by ghost** [comment]
이지트랜스 설치할 때 그냥 설치하면 설치가 안되서 안전모드에서 설치했는데 이거랑 관련이 있을까요? 이것도 상관이 없다고 하면 잘 모르겠네요.
어차피 이지트랜스 설치 경로에 놓고 쓰면 잘 되니까 그냥 이렇게 써야겠습니다.
