### ISSUE TITLE
post 요청?

### ISSUE THREAD

**Issue by gramedcart** [nanikit/eztrans-server#5]
혹시 post 요청을 사용할 수 있나요?
param을 이용하면 글자 수 제한이 있어서
post 요청 data를 이용해서 할 수 있는 방법이 있는지 궁금합니다.

**Comment by nanikit** [comment]
해당 기능은 현재 없습니다. 추가해볼게요.

**Comment by nanikit** [comment]
바디에 요청 문자열을 넣고 POST 요청을 하면 처리하도록 수정했습니다. 원하는 게 맞다면 이슈를 닫아주세요.

**Comment by gramedcart** [comment]
@nanikit
혹시 빌드해서 릴리즈로 올려주실 수 있으신가요?

**Comment by nanikit** [comment]
https://github.com/nanikit/eztrans-server/releases/tag/v220202
올렸어요.

**Comment by gramedcart** [comment]
아 감사합니다

**Comment by gramedcart** [comment]
> https://github.com/nanikit/eztrans-server/releases/tag/v220202 올렸어요.

아 감사합니다
Pre-release 를 안봤네요
